## tensorflow is very simlar to numpy but what is need of tensorfloew???

In [1]:
import tensorflow as tf



# TensorFlow:
# TensorFlow is the most popular and adopted free and open-source deep learning library. It was first developed and maintained by Google. It can be used for both research and production.


## TensorFlow benefits:
Highly efficient
Cross-platform (works on IOS, Android, Unix, Windows, in the cloud, in the browser etc etc)
Calculates gradients automatically (this is truly useful for Neural Networks, where the analytical solution of gradients would be VERY tedious to derive).
Deep integration with the Keras library (Functional approach, as well as high-level wrapper)
General notebook setup

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
tf.__version__

'2.3.1'

In [6]:
tf.executing_eagerly()

True

In [7]:
a=tf.constant(10)

In [8]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [9]:
b=tf.constant(10)

In [10]:
b

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [11]:
c=a+b

In [12]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [13]:
type(c)

tensorflow.python.framework.ops.EagerTensor

In [14]:
d = tf.Variable(20)

In [15]:
d

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>


# Intro to TensorFlow
## Core components:
1. Tensor
A Tensor in TensorFlow is an N-dimensional array (just like Numpys array object). Tensors are multilinear maps from vector spaces to real numbers. Scalars, vectors and matrices are all tensors. The Tensor represents units of data in TensorFlow.


Numpy arrays or Pandas DataFrames sent to Tensorflow functions are automatically converted into TensorFlow tensors.

2. Operations / Ops
TensorFlow operations or ops are units / edges / nodes of computation (e.g. matrix multiplication, addition, etc.)

3. Computation Graph
The computational graph is is an optimized, compiled representation of the dataflow and the order of computations that are sent to an execution environment (for example during model training).



In [16]:
from datetime import datetime
import os
import pathlib

## starting tensorboard

In [17]:
t = datetime.utcnow().strftime("%Y%m%d%H%M%S") 
log_dir = "tf_logs"
logd = "{}/r{}/".format(log_dir, t)

# Make directory if it doesn't exist

from pathlib import Path
home = str(Path.home())

logdir = os.path.join(os.sep,home,logd)

if not os.path.exists(logdir):
    os.makedirs(logdir)

In [18]:
logdir

'C:\\Users\\dell\\tf_logs/r20201125093737/'

In [19]:

a_matrix = tf.constant([[1,2], [3,4]])
b_matrix = tf.constant([[5,6], [7,8]])

In [20]:
b_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [21]:


tf.matmul(a_matrix, b_matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [22]:
print(a_matrix, b_matrix, sep="\n")

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [23]:
var = tf.Variable(3.)

In [24]:
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [25]:
var.assign(4)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=4.0>

In [26]:
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>

In [28]:
var.numpy()

4.0

In [29]:
d = tf.Variable(np.random.randn(3, 3))

In [30]:
d

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float64, numpy=
array([[-1.65015698, -0.27383661,  1.92861204],
       [-0.8906177 ,  1.04154241, -1.99128659],
       [ 1.94842575, -1.25930375,  0.42788745]])>

In [31]:

var.assign(10)
print('original value:', var.numpy())
print('add 1:', var.assign_add(1.).numpy())
print('subtract 5:', var.assign_sub(5.).numpy())

original value: 10.0
add 1: 11.0
subtract 5: 6.0


In [32]:

v = tf.Variable([[3.,3.2], [1.2,2.2]], dtype=tf.float32, name='my_variable')

print('name  : ', v.name)
print('type  : ', v.dtype)
print('shape : ', v.shape)
print('device: ', v.device)

name  :  my_variable:0
type  :  <dtype: 'float32'>
shape :  (2, 2)
device:  /job:localhost/replica:0/task:0/device:CPU:0


## 
@tf.function is a very useful module that can be used to convert simple python functions into a highly optimized computational graph that can be run on any runtime environment. When we build a model and then train it TensorFlow we can compile the model and optimize the executions.


In [35]:
@tf.function
def func2(a,b):
        z = tf.multiply(a,b, name='z')
        y1 = tf.constant(3, name='3')
        y2 = tf.constant(4)
        w1 = tf.add(z, y1, name='w1')
        w2 = tf.add(z, y2, name='w2')
        
        return(w1+w2)

In [36]:
func2(10, 20)

<tf.Tensor: shape=(), dtype=int32, numpy=407>

In [37]:
tf.multiply(10,20)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [38]:

@tf.function
def func(a,b):
    with tf.name_scope('first'):
        z = tf.multiply(a,b, name='z')
    with tf.name_scope('second'):
        y1 = tf.constant(3, name='3')
        y2 = tf.constant(4)
        w1 = tf.add(z, y1, name='w1')
        w2 = tf.add(z, y2, name='w2')
        
    return(w1+w2)

In [40]:

writer = tf.summary.create_file_writer(logdir)
tf.summary.trace_on()

In [41]:

with writer.as_default():
    tf.summary.trace_export(
        name="func2",
        step=0,
        profiler_outdir=logdir)

Instructions for updating:
use `tf.profiler.experimental.stop` instead.


In [42]:
!tensorboard --logdir $logdir

^C


In [43]:

@tf.function 
def g(x):
    y = tf.reduce_sum(x)
    if y > 0:
        return y
    return tf.abs(y)

print(tf.autograph.to_code(g.python_function))

def tf__g(x):
    with ag__.FunctionScope('g', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        y = ag__.converted_call(ag__.ld(tf).reduce_sum, (ag__.ld(x),), None, fscope)

        def get_state():
            return (retval_, do_return)

        def set_state(vars_):
            nonlocal retval_, do_return
            (retval_, do_return) = vars_

        def if_body():
            nonlocal retval_, do_return
            try:
                do_return = True
                retval_ = ag__.ld(y)
            except:
                do_return = False
                raise

        def else_body():
            nonlocal retval_, do_return
            try:
                do_return = True
                retval_ = ag__.converted_call(ag__.ld(tf).abs, (ag__.ld(y),), None, fscope)
            except:
                do_return 

In [47]:
w = tf.Variable(3.0)
with tf.GradientTape() as tape:
    expression = tf.exp(w) + 2 * w +  w * w

In [39]:
!tensorboard --logdir $logdir

^C


In [48]:

grad = tape.gradient(expression, w)
print(f'The gradient of exp at {w.numpy()} is {grad.numpy()}')

The gradient of exp at 3.0 is 28.08553695678711


In [49]:
def sigmoid(x):
    return 1/(1 + tf.exp(-x))

In [44]:


$$\sigma(x) = \frac{1}{1+e^{-x}}$$
Note that

$$\sigma'(x) = \frac{e^{-x}}{(1+e^{-x})^2} = \sigma(x)(1-\sigma(x)) $$
For instance

$$\sigma'(0) = \sigma(0)(1-\sigma(0)) = \frac{1}{2}\left(1-\frac{1}{2} \right) = \frac{1}{4}$$
In [57]:

In [58]:
#define a varaible
x = tf.Variable(0.)

#record the gradient
with tf.GradientTape() as tape:
    sig = sigmoid(x)
    
res = tape.gradient(sig, x).numpy()
print('The gradient of the sigmoid function at 0.0 is ', res)
The gradient of the sigmoid function at 0.0 is  0.25
In [ ]:


SyntaxError: invalid syntax (<ipython-input-44-b374093a0b95>, line 6)