In [2]:
import numpy as np

In [3]:
it = [3,6,7,11]

In [4]:
n = np.array(it)

In [5]:
type(n)

numpy.ndarray

In [6]:
n



array([ 3,  6,  7, 11])

In [7]:
type(n)

numpy.ndarray

In [8]:
d = {"apple" : "A swwet red fruit" , "mango" : "king of fruit"}

In [9]:
d

{'apple': 'A swwet red fruit', 'mango': 'king of fruit'}

In [10]:
np.array(d)

array({'apple': 'A swwet red fruit', 'mango': 'king of fruit'},
      dtype=object)

In [11]:
ond = np.array([[1,2,3,4],[1,2,9,5]])

In [12]:
ond

array([[1, 2, 3, 4],
       [1, 2, 9, 5]])

In [13]:
err = np.array([[1,2,3,4],[1,2,5]])

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


## this is comming here one elemnet taking 4 element and other taking 3 eleement so it is not able to cancatinate them properly and form them into a list

In [14]:
y = np.array([2,3,5,"fg"])

In [15]:
y

array(['2', '3', '5', 'fg'], dtype='<U11')

In [16]:
l = np.array([2,3,5,'fg'])

In [17]:
l

array(['2', '3', '5', 'fg'], dtype='<U11')

In [18]:
ond = np.array([[1,2,3,4],[1,2,9,5]])

In [19]:
a = np.arange(15).reshape(3,5)

In [20]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
b = np.arange(15).reshape(5,3)

In [22]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
c= np.arange(5)

In [24]:
c


array([0, 1, 2, 3, 4])

In [25]:
d= np.arange(8,76)

In [26]:
d


array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])

In [27]:
e = np.arange(8,76,9)

In [28]:
e


array([ 8, 17, 26, 35, 44, 53, 62, 71])

## question mark trick

In [29]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

In [30]:
np.range?

Object `np.range` not found.


In [32]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
arr1 = np.arange(40)

In [35]:
arr2 = arr1.reshape(8,5)

In [36]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [38]:
arr1[0] = 1000

In [39]:
arr1


array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39])

In [40]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [41]:
arr2.dtype


dtype('int32')

In [51]:
a= np.random.randint(1,10,(2,10))

In [52]:
a

array([[4, 1, 7, 1, 5, 8, 1, 5, 2, 1],
       [2, 9, 8, 4, 2, 8, 6, 1, 6, 8]])

In [53]:
b= np.random.randint(1,10,(2,10))

In [54]:
b

array([[4, 3, 8, 5, 9, 5, 3, 6, 5, 6],
       [5, 2, 1, 9, 4, 7, 3, 2, 1, 4]])

In [55]:
c = a+b

In [57]:
c

array([[ 8,  4, 15,  6, 14, 13,  4, 11,  7,  7],
       [ 7, 11,  9, 13,  6, 15,  9,  3,  7, 12]])


## concept of broadcasting

In [75]:
d= np.random.randint(1,10,(3,6))

In [76]:
e= np.random.randint(1,10,(2,4))

In [77]:
d+e

ValueError: operands could not be broadcast together with shapes (3,6) (2,4) 

In [78]:
d= np.random.randint(1,10,(4))

In [79]:
e= np.random.randint(1,10,(2,4))

In [80]:
d+e

array([[10, 11,  8,  9],
       [14,  4, 11, 10]])

In [82]:
f= np.random.randint(1,10,(2,4))

In [83]:
g =np.random.randint(1,10,(300,2,1))

In [84]:
f+g

array([[[12,  9, 15, 15],
        [12,  9, 15,  9]],

       [[10,  7, 13, 13],
        [ 6,  3,  9,  3]],

       [[15, 12, 18, 18],
        [ 8,  5, 11,  5]],

       ...,

       [[ 7,  4, 10, 10],
        [13, 10, 16, 10]],

       [[15, 12, 18, 18],
        [10,  7, 13,  7]],

       [[14, 11, 17, 17],
        [14, 11, 17, 11]]])

## broadcasting rules

In [85]:
# shape should be same,start checking from the left
# if it has 1 , then cool