In [1]:
import numpy as np

In [2]:
it = [3,6,7,11]

In [3]:
n = np.array(it)

In [4]:
type(n)

numpy.ndarray

In [7]:
n



array([ 3,  6,  7, 11])

In [8]:
type(n)

numpy.ndarray

In [9]:
d = {"apple" : "A swwet red fruit" , "mango" : "king of fruit"}

In [10]:
d

{'apple': 'A swwet red fruit', 'mango': 'king of fruit'}

In [11]:
np.array(d)

array({'apple': 'A swwet red fruit', 'mango': 'king of fruit'},
      dtype=object)

In [21]:
ond = np.array([[1,2,3,4],[1,2,9,5]])

In [22]:
ond

array([[1, 2, 3, 4],
       [1, 2, 9, 5]])

In [23]:
err = np.array([[1,2,3,4],[1,2,5]])

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


## this is comming here one elemnet taking 4 element and other taking 3 eleement so it is not able to cancatinate them properly and form them into a list

In [26]:
y = np.array([2,3,5,"fg"])

In [27]:
y

array(['2', '3', '5', 'fg'], dtype='<U11')

In [28]:
l = np.array([2,3,5,'fg'])

In [29]:
l

array(['2', '3', '5', 'fg'], dtype='<U11')

In [30]:
ond = np.array([[1,2,3,4],[1,2,9,5]])

In [31]:
a = np.arange(15).reshape(3,5)

In [32]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
b = np.arange(15).reshape(5,3)

In [34]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
c= np.arange(5)

In [36]:
c


array([0, 1, 2, 3, 4])

In [38]:
d= np.arange(8,76)

In [39]:
d


array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])

In [40]:
e = np.arange(8,76,9)

In [41]:
e


array([ 8, 17, 26, 35, 44, 53, 62, 71])

## question mark trick

In [44]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

In [45]:
np.range?

Object `np.range` not found.
