In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## data preprocessing

In [2]:
datasets=pd.read_csv("data.csv")

In [3]:
x=datasets.iloc[:,:-1].values

In [4]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
y=datasets.iloc[:,3].values

In [6]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [9]:
from sklearn.preprocessing import Imputer

In [10]:
imputer=Imputer(missing_values="NaN",strategy= "mean", axis=0)


c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [11]:
imputer=imputer.fit(x[:,1:3])

In [12]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [13]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## label encoder 


In [14]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [15]:
labelencoder_x=LabelEncoder()

In [16]:
x[:,0]=labelencoder_x.fit_transform(x[:,0])


In [17]:
x[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [18]:
onehotencoder=OneHotEncoder(categorical_features=[0])


In [19]:
x=onehotencoder.fit_transform(x).toarray()

c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [20]:
x[:,0]=labelencoder_x.fit_transform(x[:,0])


In [22]:
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [21]:
!pip install sklearn

In [24]:
from sklearn.model_selection import train_test_split 

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
from sklearn.preprocessing import StandardScaler


In [27]:
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [28]:
x_test

array([[0.00000000e+00, 1.00000000e+00, 2.77555756e-17, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 2.77555756e-17, 5.00000000e+01,
        8.30000000e+04]])