In [1]:
import numpy as np

In [2]:
np.random.random()

0.6390749062850091

In [3]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k

In [4]:
np.random.randint(0,10)

8

In [5]:
np.random.randint(0,10,20)

array([8, 1, 1, 2, 5, 3, 6, 4, 0, 7, 2, 2, 9, 3, 5, 6, 7, 0, 2, 9])

In [15]:
np.random.randint(0,10,(4,5))

array([[0, 9, 7, 7, 0],
       [0, 4, 7, 5, 0],
       [3, 6, 3, 0, 8],
       [8, 7, 4, 2, 8]])

##   np.random.randn(1000) has mean 0 and aproz standard deviation 0

In [16]:
data=np.random.randn(1000)

In [17]:
data.mean()

0.013659201203791552

In [18]:
data.std()

1.0207475122279968

## aproxx value 

## 3d munpt array generation

In [20]:
np.random.randint(0,10,(4,5,3))

array([[[1, 9, 4],
        [7, 5, 1],
        [3, 3, 0],
        [6, 5, 5],
        [2, 8, 6]],

       [[4, 3, 6],
        [9, 8, 6],
        [3, 7, 1],
        [0, 6, 5],
        [8, 0, 5]],

       [[3, 4, 1],
        [2, 7, 4],
        [3, 6, 1],
        [9, 9, 9],
        [8, 1, 2]],

       [[1, 9, 9],
        [6, 0, 7],
        [6, 2, 3],
        [1, 7, 8],
        [4, 6, 5]]])

In [30]:
a=np.random.randint(0,10,(4,5))

In [32]:
a.shape

(4, 5)

In [33]:
a.size

20

In [36]:
a

array([[1, 3, 1, 4, 9],
       [3, 7, 7, 4, 0],
       [0, 0, 5, 6, 4],
       [1, 6, 2, 7, 2]])

## along the column

In [35]:
a.sum(axis =1)

array([18, 21, 15, 18])

## along the row

In [38]:
a.sum(axis =0 )

array([ 5, 16, 15, 21, 15])

## keepdimension parameter

In [41]:
a.sum(axis =0 ,keepdims=True).shape

(1, 5)

In [42]:
a.sum(axis =0).shape

(5,)

In [46]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

In [48]:
k=np.linspace(0,2 * np.pi ,100)

In [49]:
k

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [50]:
y=np.sin(x)

NameError: name 'x' is not defined